version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "zacky1972"
    schedule: 
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    reviewers:
      - "zacky1972"
    schedule: 
      interval: "daily"
